// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"review/internal/service"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPullReqRepo creates a new instance of MockPullReqRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPullReqRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPullReqRepo {
	mock := &MockPullReqRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPullReqRepo is an autogenerated mock type for the PullReqRepo type
type MockPullReqRepo struct {
	mock.Mock
}

type MockPullReqRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPullReqRepo) EXPECT() *MockPullReqRepo_Expecter {
	return &MockPullReqRepo_Expecter{mock: &_m.Mock}
}

// AssignPullReqReviewers provides a mock function for the type MockPullReqRepo
func (_mock *MockPullReqRepo) AssignPullReqReviewers(ctx context.Context, pullReqId string, reviewers []service.User) error {
	ret := _mock.Called(ctx, pullReqId, reviewers)

	if len(ret) == 0 {
		panic("no return value specified for AssignPullReqReviewers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []service.User) error); ok {
		r0 = returnFunc(ctx, pullReqId, reviewers)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPullReqRepo_AssignPullReqReviewers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignPullReqReviewers'
type MockPullReqRepo_AssignPullReqReviewers_Call struct {
	*mock.Call
}

// AssignPullReqReviewers is a helper method to define mock.On call
//   - ctx context.Context
//   - pullReqId string
//   - reviewers []service.User
func (_e *MockPullReqRepo_Expecter) AssignPullReqReviewers(ctx interface{}, pullReqId interface{}, reviewers interface{}) *MockPullReqRepo_AssignPullReqReviewers_Call {
	return &MockPullReqRepo_AssignPullReqReviewers_Call{Call: _e.mock.On("AssignPullReqReviewers", ctx, pullReqId, reviewers)}
}

func (_c *MockPullReqRepo_AssignPullReqReviewers_Call) Run(run func(ctx context.Context, pullReqId string, reviewers []service.User)) *MockPullReqRepo_AssignPullReqReviewers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []service.User
		if args[2] != nil {
			arg2 = args[2].([]service.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPullReqRepo_AssignPullReqReviewers_Call) Return(err error) *MockPullReqRepo_AssignPullReqReviewers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPullReqRepo_AssignPullReqReviewers_Call) RunAndReturn(run func(ctx context.Context, pullReqId string, reviewers []service.User) error) *MockPullReqRepo_AssignPullReqReviewers_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePullReq provides a mock function for the type MockPullReqRepo
func (_mock *MockPullReqRepo) CreatePullReq(ctx context.Context, pullReqId string, name string, authorId string) error {
	ret := _mock.Called(ctx, pullReqId, name, authorId)

	if len(ret) == 0 {
		panic("no return value specified for CreatePullReq")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, pullReqId, name, authorId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPullReqRepo_CreatePullReq_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePullReq'
type MockPullReqRepo_CreatePullReq_Call struct {
	*mock.Call
}

// CreatePullReq is a helper method to define mock.On call
//   - ctx context.Context
//   - pullReqId string
//   - name string
//   - authorId string
func (_e *MockPullReqRepo_Expecter) CreatePullReq(ctx interface{}, pullReqId interface{}, name interface{}, authorId interface{}) *MockPullReqRepo_CreatePullReq_Call {
	return &MockPullReqRepo_CreatePullReq_Call{Call: _e.mock.On("CreatePullReq", ctx, pullReqId, name, authorId)}
}

func (_c *MockPullReqRepo_CreatePullReq_Call) Run(run func(ctx context.Context, pullReqId string, name string, authorId string)) *MockPullReqRepo_CreatePullReq_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPullReqRepo_CreatePullReq_Call) Return(err error) *MockPullReqRepo_CreatePullReq_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPullReqRepo_CreatePullReq_Call) RunAndReturn(run func(ctx context.Context, pullReqId string, name string, authorId string) error) *MockPullReqRepo_CreatePullReq_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersToAssign provides a mock function for the type MockPullReqRepo
func (_mock *MockPullReqRepo) GetUsersToAssign(ctx context.Context, authorId string) ([]service.User, error) {
	ret := _mock.Called(ctx, authorId)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersToAssign")
	}

	var r0 []service.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]service.User, error)); ok {
		return returnFunc(ctx, authorId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []service.User); ok {
		r0 = returnFunc(ctx, authorId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, authorId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPullReqRepo_GetUsersToAssign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersToAssign'
type MockPullReqRepo_GetUsersToAssign_Call struct {
	*mock.Call
}

// GetUsersToAssign is a helper method to define mock.On call
//   - ctx context.Context
//   - authorId string
func (_e *MockPullReqRepo_Expecter) GetUsersToAssign(ctx interface{}, authorId interface{}) *MockPullReqRepo_GetUsersToAssign_Call {
	return &MockPullReqRepo_GetUsersToAssign_Call{Call: _e.mock.On("GetUsersToAssign", ctx, authorId)}
}

func (_c *MockPullReqRepo_GetUsersToAssign_Call) Run(run func(ctx context.Context, authorId string)) *MockPullReqRepo_GetUsersToAssign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullReqRepo_GetUsersToAssign_Call) Return(users []service.User, err error) *MockPullReqRepo_GetUsersToAssign_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockPullReqRepo_GetUsersToAssign_Call) RunAndReturn(run func(ctx context.Context, authorId string) ([]service.User, error)) *MockPullReqRepo_GetUsersToAssign_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPullReqMerged provides a mock function for the type MockPullReqRepo
func (_mock *MockPullReqRepo) MarkPullReqMerged(ctx context.Context, pullReqId string) error {
	ret := _mock.Called(ctx, pullReqId)

	if len(ret) == 0 {
		panic("no return value specified for MarkPullReqMerged")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, pullReqId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPullReqRepo_MarkPullReqMerged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPullReqMerged'
type MockPullReqRepo_MarkPullReqMerged_Call struct {
	*mock.Call
}

// MarkPullReqMerged is a helper method to define mock.On call
//   - ctx context.Context
//   - pullReqId string
func (_e *MockPullReqRepo_Expecter) MarkPullReqMerged(ctx interface{}, pullReqId interface{}) *MockPullReqRepo_MarkPullReqMerged_Call {
	return &MockPullReqRepo_MarkPullReqMerged_Call{Call: _e.mock.On("MarkPullReqMerged", ctx, pullReqId)}
}

func (_c *MockPullReqRepo_MarkPullReqMerged_Call) Run(run func(ctx context.Context, pullReqId string)) *MockPullReqRepo_MarkPullReqMerged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullReqRepo_MarkPullReqMerged_Call) Return(err error) *MockPullReqRepo_MarkPullReqMerged_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPullReqRepo_MarkPullReqMerged_Call) RunAndReturn(run func(ctx context.Context, pullReqId string) error) *MockPullReqRepo_MarkPullReqMerged_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTeamRepo creates a new instance of MockTeamRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamRepo {
	mock := &MockTeamRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTeamRepo is an autogenerated mock type for the TeamRepo type
type MockTeamRepo struct {
	mock.Mock
}

type MockTeamRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamRepo) EXPECT() *MockTeamRepo_Expecter {
	return &MockTeamRepo_Expecter{mock: &_m.Mock}
}

// AddTeam provides a mock function for the type MockTeamRepo
func (_mock *MockTeamRepo) AddTeam(ctx context.Context, name string, members []service.User) error {
	ret := _mock.Called(ctx, name, members)

	if len(ret) == 0 {
		panic("no return value specified for AddTeam")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []service.User) error); ok {
		r0 = returnFunc(ctx, name, members)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTeamRepo_AddTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTeam'
type MockTeamRepo_AddTeam_Call struct {
	*mock.Call
}

// AddTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - members []service.User
func (_e *MockTeamRepo_Expecter) AddTeam(ctx interface{}, name interface{}, members interface{}) *MockTeamRepo_AddTeam_Call {
	return &MockTeamRepo_AddTeam_Call{Call: _e.mock.On("AddTeam", ctx, name, members)}
}

func (_c *MockTeamRepo_AddTeam_Call) Run(run func(ctx context.Context, name string, members []service.User)) *MockTeamRepo_AddTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []service.User
		if args[2] != nil {
			arg2 = args[2].([]service.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTeamRepo_AddTeam_Call) Return(err error) *MockTeamRepo_AddTeam_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTeamRepo_AddTeam_Call) RunAndReturn(run func(ctx context.Context, name string, members []service.User) error) *MockTeamRepo_AddTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeam provides a mock function for the type MockTeamRepo
func (_mock *MockTeamRepo) GetTeam(ctx context.Context, name string) (*service.Team, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetTeam")
	}

	var r0 *service.Team
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*service.Team, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *service.Team); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Team)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepo_GetTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeam'
type MockTeamRepo_GetTeam_Call struct {
	*mock.Call
}

// GetTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTeamRepo_Expecter) GetTeam(ctx interface{}, name interface{}) *MockTeamRepo_GetTeam_Call {
	return &MockTeamRepo_GetTeam_Call{Call: _e.mock.On("GetTeam", ctx, name)}
}

func (_c *MockTeamRepo_GetTeam_Call) Run(run func(ctx context.Context, name string)) *MockTeamRepo_GetTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepo_GetTeam_Call) Return(team *service.Team, err error) *MockTeamRepo_GetTeam_Call {
	_c.Call.Return(team, err)
	return _c
}

func (_c *MockTeamRepo_GetTeam_Call) RunAndReturn(run func(ctx context.Context, name string) (*service.Team, error)) *MockTeamRepo_GetTeam_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepo creates a new instance of MockUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepo {
	mock := &MockUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepo is an autogenerated mock type for the UserRepo type
type MockUserRepo struct {
	mock.Mock
}

type MockUserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepo) EXPECT() *MockUserRepo_Expecter {
	return &MockUserRepo_Expecter{mock: &_m.Mock}
}

// GetReviewAssignments provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetReviewAssignments(ctx context.Context, id string) ([]service.PullReq, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetReviewAssignments")
	}

	var r0 []service.PullReq
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]service.PullReq, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []service.PullReq); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.PullReq)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetReviewAssignments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReviewAssignments'
type MockUserRepo_GetReviewAssignments_Call struct {
	*mock.Call
}

// GetReviewAssignments is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserRepo_Expecter) GetReviewAssignments(ctx interface{}, id interface{}) *MockUserRepo_GetReviewAssignments_Call {
	return &MockUserRepo_GetReviewAssignments_Call{Call: _e.mock.On("GetReviewAssignments", ctx, id)}
}

func (_c *MockUserRepo_GetReviewAssignments_Call) Run(run func(ctx context.Context, id string)) *MockUserRepo_GetReviewAssignments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetReviewAssignments_Call) Return(pullReqs []service.PullReq, err error) *MockUserRepo_GetReviewAssignments_Call {
	_c.Call.Return(pullReqs, err)
	return _c
}

func (_c *MockUserRepo_GetReviewAssignments_Call) RunAndReturn(run func(ctx context.Context, id string) ([]service.PullReq, error)) *MockUserRepo_GetReviewAssignments_Call {
	_c.Call.Return(run)
	return _c
}

// SetIsActiveUser provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) SetIsActiveUser(ctx context.Context, id string, isActive bool) error {
	ret := _mock.Called(ctx, id, isActive)

	if len(ret) == 0 {
		panic("no return value specified for SetIsActiveUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, id, isActive)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_SetIsActiveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetIsActiveUser'
type MockUserRepo_SetIsActiveUser_Call struct {
	*mock.Call
}

// SetIsActiveUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - isActive bool
func (_e *MockUserRepo_Expecter) SetIsActiveUser(ctx interface{}, id interface{}, isActive interface{}) *MockUserRepo_SetIsActiveUser_Call {
	return &MockUserRepo_SetIsActiveUser_Call{Call: _e.mock.On("SetIsActiveUser", ctx, id, isActive)}
}

func (_c *MockUserRepo_SetIsActiveUser_Call) Run(run func(ctx context.Context, id string, isActive bool)) *MockUserRepo_SetIsActiveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepo_SetIsActiveUser_Call) Return(err error) *MockUserRepo_SetIsActiveUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_SetIsActiveUser_Call) RunAndReturn(run func(ctx context.Context, id string, isActive bool) error) *MockUserRepo_SetIsActiveUser_Call {
	_c.Call.Return(run)
	return _c
}
