// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"review/internal/service"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTeamRepo creates a new instance of MockTeamRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTeamRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTeamRepo {
	mock := &MockTeamRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTeamRepo is an autogenerated mock type for the TeamRepo type
type MockTeamRepo struct {
	mock.Mock
}

type MockTeamRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTeamRepo) EXPECT() *MockTeamRepo_Expecter {
	return &MockTeamRepo_Expecter{mock: &_m.Mock}
}

// AddTeam provides a mock function for the type MockTeamRepo
func (_mock *MockTeamRepo) AddTeam(ctx context.Context, name string, members []service.User) error {
	ret := _mock.Called(ctx, name, members)

	if len(ret) == 0 {
		panic("no return value specified for AddTeam")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []service.User) error); ok {
		r0 = returnFunc(ctx, name, members)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTeamRepo_AddTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTeam'
type MockTeamRepo_AddTeam_Call struct {
	*mock.Call
}

// AddTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - members []service.User
func (_e *MockTeamRepo_Expecter) AddTeam(ctx interface{}, name interface{}, members interface{}) *MockTeamRepo_AddTeam_Call {
	return &MockTeamRepo_AddTeam_Call{Call: _e.mock.On("AddTeam", ctx, name, members)}
}

func (_c *MockTeamRepo_AddTeam_Call) Run(run func(ctx context.Context, name string, members []service.User)) *MockTeamRepo_AddTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []service.User
		if args[2] != nil {
			arg2 = args[2].([]service.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTeamRepo_AddTeam_Call) Return(err error) *MockTeamRepo_AddTeam_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTeamRepo_AddTeam_Call) RunAndReturn(run func(ctx context.Context, name string, members []service.User) error) *MockTeamRepo_AddTeam_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeam provides a mock function for the type MockTeamRepo
func (_mock *MockTeamRepo) GetTeam(ctx context.Context, name string) (*service.Team, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetTeam")
	}

	var r0 *service.Team
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*service.Team, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *service.Team); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Team)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTeamRepo_GetTeam_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeam'
type MockTeamRepo_GetTeam_Call struct {
	*mock.Call
}

// GetTeam is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTeamRepo_Expecter) GetTeam(ctx interface{}, name interface{}) *MockTeamRepo_GetTeam_Call {
	return &MockTeamRepo_GetTeam_Call{Call: _e.mock.On("GetTeam", ctx, name)}
}

func (_c *MockTeamRepo_GetTeam_Call) Run(run func(ctx context.Context, name string)) *MockTeamRepo_GetTeam_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTeamRepo_GetTeam_Call) Return(team *service.Team, err error) *MockTeamRepo_GetTeam_Call {
	_c.Call.Return(team, err)
	return _c
}

func (_c *MockTeamRepo_GetTeam_Call) RunAndReturn(run func(ctx context.Context, name string) (*service.Team, error)) *MockTeamRepo_GetTeam_Call {
	_c.Call.Return(run)
	return _c
}
