// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"review/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPullReqRepo creates a new instance of MockPullReqRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPullReqRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPullReqRepo {
	mock := &MockPullReqRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPullReqRepo is an autogenerated mock type for the PullReqRepo type
type MockPullReqRepo struct {
	mock.Mock
}

type MockPullReqRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPullReqRepo) EXPECT() *MockPullReqRepo_Expecter {
	return &MockPullReqRepo_Expecter{mock: &_m.Mock}
}

// AssignPullReqReviewers provides a mock function for the type MockPullReqRepo
func (_mock *MockPullReqRepo) AssignPullReqReviewers(ctx context.Context, pullReqId string, reviewers []domain.User) error {
	ret := _mock.Called(ctx, pullReqId, reviewers)

	if len(ret) == 0 {
		panic("no return value specified for AssignPullReqReviewers")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []domain.User) error); ok {
		r0 = returnFunc(ctx, pullReqId, reviewers)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPullReqRepo_AssignPullReqReviewers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignPullReqReviewers'
type MockPullReqRepo_AssignPullReqReviewers_Call struct {
	*mock.Call
}

// AssignPullReqReviewers is a helper method to define mock.On call
//   - ctx context.Context
//   - pullReqId string
//   - reviewers []domain.User
func (_e *MockPullReqRepo_Expecter) AssignPullReqReviewers(ctx interface{}, pullReqId interface{}, reviewers interface{}) *MockPullReqRepo_AssignPullReqReviewers_Call {
	return &MockPullReqRepo_AssignPullReqReviewers_Call{Call: _e.mock.On("AssignPullReqReviewers", ctx, pullReqId, reviewers)}
}

func (_c *MockPullReqRepo_AssignPullReqReviewers_Call) Run(run func(ctx context.Context, pullReqId string, reviewers []domain.User)) *MockPullReqRepo_AssignPullReqReviewers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []domain.User
		if args[2] != nil {
			arg2 = args[2].([]domain.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPullReqRepo_AssignPullReqReviewers_Call) Return(err error) *MockPullReqRepo_AssignPullReqReviewers_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPullReqRepo_AssignPullReqReviewers_Call) RunAndReturn(run func(ctx context.Context, pullReqId string, reviewers []domain.User) error) *MockPullReqRepo_AssignPullReqReviewers_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePullReq provides a mock function for the type MockPullReqRepo
func (_mock *MockPullReqRepo) CreatePullReq(ctx context.Context, pullReqId string, name string, authorId string) error {
	ret := _mock.Called(ctx, pullReqId, name, authorId)

	if len(ret) == 0 {
		panic("no return value specified for CreatePullReq")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, pullReqId, name, authorId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPullReqRepo_CreatePullReq_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePullReq'
type MockPullReqRepo_CreatePullReq_Call struct {
	*mock.Call
}

// CreatePullReq is a helper method to define mock.On call
//   - ctx context.Context
//   - pullReqId string
//   - name string
//   - authorId string
func (_e *MockPullReqRepo_Expecter) CreatePullReq(ctx interface{}, pullReqId interface{}, name interface{}, authorId interface{}) *MockPullReqRepo_CreatePullReq_Call {
	return &MockPullReqRepo_CreatePullReq_Call{Call: _e.mock.On("CreatePullReq", ctx, pullReqId, name, authorId)}
}

func (_c *MockPullReqRepo_CreatePullReq_Call) Run(run func(ctx context.Context, pullReqId string, name string, authorId string)) *MockPullReqRepo_CreatePullReq_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPullReqRepo_CreatePullReq_Call) Return(err error) *MockPullReqRepo_CreatePullReq_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPullReqRepo_CreatePullReq_Call) RunAndReturn(run func(ctx context.Context, pullReqId string, name string, authorId string) error) *MockPullReqRepo_CreatePullReq_Call {
	_c.Call.Return(run)
	return _c
}

// GetPullReq provides a mock function for the type MockPullReqRepo
func (_mock *MockPullReqRepo) GetPullReq(ctx context.Context, pullReqId string) (domain.PullReq, error) {
	ret := _mock.Called(ctx, pullReqId)

	if len(ret) == 0 {
		panic("no return value specified for GetPullReq")
	}

	var r0 domain.PullReq
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.PullReq, error)); ok {
		return returnFunc(ctx, pullReqId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.PullReq); ok {
		r0 = returnFunc(ctx, pullReqId)
	} else {
		r0 = ret.Get(0).(domain.PullReq)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, pullReqId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPullReqRepo_GetPullReq_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPullReq'
type MockPullReqRepo_GetPullReq_Call struct {
	*mock.Call
}

// GetPullReq is a helper method to define mock.On call
//   - ctx context.Context
//   - pullReqId string
func (_e *MockPullReqRepo_Expecter) GetPullReq(ctx interface{}, pullReqId interface{}) *MockPullReqRepo_GetPullReq_Call {
	return &MockPullReqRepo_GetPullReq_Call{Call: _e.mock.On("GetPullReq", ctx, pullReqId)}
}

func (_c *MockPullReqRepo_GetPullReq_Call) Run(run func(ctx context.Context, pullReqId string)) *MockPullReqRepo_GetPullReq_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullReqRepo_GetPullReq_Call) Return(pullReq domain.PullReq, err error) *MockPullReqRepo_GetPullReq_Call {
	_c.Call.Return(pullReq, err)
	return _c
}

func (_c *MockPullReqRepo_GetPullReq_Call) RunAndReturn(run func(ctx context.Context, pullReqId string) (domain.PullReq, error)) *MockPullReqRepo_GetPullReq_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersToAssign provides a mock function for the type MockPullReqRepo
func (_mock *MockPullReqRepo) GetUsersToAssign(ctx context.Context, authorId string) ([]domain.User, error) {
	ret := _mock.Called(ctx, authorId)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersToAssign")
	}

	var r0 []domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.User, error)); ok {
		return returnFunc(ctx, authorId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.User); ok {
		r0 = returnFunc(ctx, authorId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, authorId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPullReqRepo_GetUsersToAssign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersToAssign'
type MockPullReqRepo_GetUsersToAssign_Call struct {
	*mock.Call
}

// GetUsersToAssign is a helper method to define mock.On call
//   - ctx context.Context
//   - authorId string
func (_e *MockPullReqRepo_Expecter) GetUsersToAssign(ctx interface{}, authorId interface{}) *MockPullReqRepo_GetUsersToAssign_Call {
	return &MockPullReqRepo_GetUsersToAssign_Call{Call: _e.mock.On("GetUsersToAssign", ctx, authorId)}
}

func (_c *MockPullReqRepo_GetUsersToAssign_Call) Run(run func(ctx context.Context, authorId string)) *MockPullReqRepo_GetUsersToAssign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullReqRepo_GetUsersToAssign_Call) Return(users []domain.User, err error) *MockPullReqRepo_GetUsersToAssign_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockPullReqRepo_GetUsersToAssign_Call) RunAndReturn(run func(ctx context.Context, authorId string) ([]domain.User, error)) *MockPullReqRepo_GetUsersToAssign_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPullReqMerged provides a mock function for the type MockPullReqRepo
func (_mock *MockPullReqRepo) MarkPullReqMerged(ctx context.Context, pullReqId string) error {
	ret := _mock.Called(ctx, pullReqId)

	if len(ret) == 0 {
		panic("no return value specified for MarkPullReqMerged")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, pullReqId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPullReqRepo_MarkPullReqMerged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPullReqMerged'
type MockPullReqRepo_MarkPullReqMerged_Call struct {
	*mock.Call
}

// MarkPullReqMerged is a helper method to define mock.On call
//   - ctx context.Context
//   - pullReqId string
func (_e *MockPullReqRepo_Expecter) MarkPullReqMerged(ctx interface{}, pullReqId interface{}) *MockPullReqRepo_MarkPullReqMerged_Call {
	return &MockPullReqRepo_MarkPullReqMerged_Call{Call: _e.mock.On("MarkPullReqMerged", ctx, pullReqId)}
}

func (_c *MockPullReqRepo_MarkPullReqMerged_Call) Run(run func(ctx context.Context, pullReqId string)) *MockPullReqRepo_MarkPullReqMerged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPullReqRepo_MarkPullReqMerged_Call) Return(err error) *MockPullReqRepo_MarkPullReqMerged_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPullReqRepo_MarkPullReqMerged_Call) RunAndReturn(run func(ctx context.Context, pullReqId string) error) *MockPullReqRepo_MarkPullReqMerged_Call {
	_c.Call.Return(run)
	return _c
}
