// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"review/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepo creates a new instance of MockUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepo {
	mock := &MockUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepo is an autogenerated mock type for the UserRepo type
type MockUserRepo struct {
	mock.Mock
}

type MockUserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepo) EXPECT() *MockUserRepo_Expecter {
	return &MockUserRepo_Expecter{mock: &_m.Mock}
}

// GetReviewAssignments provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetReviewAssignments(ctx context.Context, id string) ([]domain.PullReq, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetReviewAssignments")
	}

	var r0 []domain.PullReq
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.PullReq, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.PullReq); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PullReq)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetReviewAssignments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReviewAssignments'
type MockUserRepo_GetReviewAssignments_Call struct {
	*mock.Call
}

// GetReviewAssignments is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserRepo_Expecter) GetReviewAssignments(ctx interface{}, id interface{}) *MockUserRepo_GetReviewAssignments_Call {
	return &MockUserRepo_GetReviewAssignments_Call{Call: _e.mock.On("GetReviewAssignments", ctx, id)}
}

func (_c *MockUserRepo_GetReviewAssignments_Call) Run(run func(ctx context.Context, id string)) *MockUserRepo_GetReviewAssignments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetReviewAssignments_Call) Return(pullReqs []domain.PullReq, err error) *MockUserRepo_GetReviewAssignments_Call {
	_c.Call.Return(pullReqs, err)
	return _c
}

func (_c *MockUserRepo_GetReviewAssignments_Call) RunAndReturn(run func(ctx context.Context, id string) ([]domain.PullReq, error)) *MockUserRepo_GetReviewAssignments_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetUser(ctx context.Context, id string) (*domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUserRepo_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserRepo_Expecter) GetUser(ctx interface{}, id interface{}) *MockUserRepo_GetUser_Call {
	return &MockUserRepo_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *MockUserRepo_GetUser_Call) Run(run func(ctx context.Context, id string)) *MockUserRepo_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetUser_Call) Return(user *domain.User, err error) *MockUserRepo_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_GetUser_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.User, error)) *MockUserRepo_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// SetIsActiveUser provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) SetIsActiveUser(ctx context.Context, id string, isActive bool) error {
	ret := _mock.Called(ctx, id, isActive)

	if len(ret) == 0 {
		panic("no return value specified for SetIsActiveUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, id, isActive)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepo_SetIsActiveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetIsActiveUser'
type MockUserRepo_SetIsActiveUser_Call struct {
	*mock.Call
}

// SetIsActiveUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - isActive bool
func (_e *MockUserRepo_Expecter) SetIsActiveUser(ctx interface{}, id interface{}, isActive interface{}) *MockUserRepo_SetIsActiveUser_Call {
	return &MockUserRepo_SetIsActiveUser_Call{Call: _e.mock.On("SetIsActiveUser", ctx, id, isActive)}
}

func (_c *MockUserRepo_SetIsActiveUser_Call) Run(run func(ctx context.Context, id string, isActive bool)) *MockUserRepo_SetIsActiveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepo_SetIsActiveUser_Call) Return(err error) *MockUserRepo_SetIsActiveUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepo_SetIsActiveUser_Call) RunAndReturn(run func(ctx context.Context, id string, isActive bool) error) *MockUserRepo_SetIsActiveUser_Call {
	_c.Call.Return(run)
	return _c
}
